<?php

declare(strict_types=1);

namespace Forwext\Tools\Addon;

use Forwext\Core\Addon\AddonId;
use Forwext\Core\Addon\AddonManifest;
use Forwext\Core\Addon\AddonVersion;
use InvalidArgumentException;
use JsonException;
use RuntimeException;

final readonly class AddonScaffolder
{
    public function __construct(private string $projectRoot)
    {
    }

    /** @return list<string> */
    public function create(AddonId $id, AddonVersion $version): array
    {
        $root = $this->projectRoot();
        $addons = $root . DIRECTORY_SEPARATOR . 'addons';
        $this->ensureDirectory($addons);

        $target = $addons . DIRECTORY_SEPARATOR . $id->vendor() . DIRECTORY_SEPARATOR . $id->name();
        if (file_exists($target) || is_link($target)) {
            throw new InvalidArgumentException('Add-on directory already exists: ' . $target);
        }

        $forwextVersion = trim((string) file_get_contents($root . DIRECTORY_SEPARATOR . 'VERSION'));
        if ($forwextVersion === '') {
            throw new RuntimeException('Forwext VERSION is unavailable.');
        }

        $manifest = [
            'id'=>$id->value(),
            'version'=>$version->value(),
            'title'=>$id->name(),
            'description'=>$id->name() . ' add-on for Forwext.',
            'requires'=>[
                'forwext'=>$forwextVersion,
                'addons'=>[],
            ],
            'conflicts'=>[
                'addons'=>[],
            ],
            'data_retention'=>'retain_only',
            'capabilities'=>[],
        ];

        try {
            $manifestJson = json_encode(
                $manifest,
                JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,
            ) . "\n";
        } catch (JsonException $exception) {
            throw new RuntimeException('Unable to encode add-on manifest.', previous:$exception);
        }
        AddonManifest::fromJson($manifestJson);

        $namespace = $id->vendor() . '\\' . $id->name();
        $composer = [
            'name'=>strtolower($id->vendor() . '/' . $id->name()),
            'type'=>'forwext-addon',
            'require'=>[
                'php'=>'>=8.4',
            ],
            'autoload'=>[
                'psr-4'=>[
                    $namespace . '\\'=>'src/',
                ],
            ],
        ];
        try {
            $composerJson = json_encode(
                $composer,
                JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES,
            ) . "\n";
        } catch (JsonException $exception) {
            throw new RuntimeException('Unable to encode add-on Composer metadata.', previous:$exception);
        }

        $extension = "<?php\n\ndeclare(strict_types=1);\n\nnamespace {$namespace};\n\n"
            . "final readonly class Extension\n{\n"
            . "    public const ID = '" . $id->value() . "';\n"
            . "}\n";

        $readme = '# ' . $id->value() . "\n\n"
            . "Generated by the Forwext Developer CLI.\n\n"
            . "- Minimum PHP: 8.4\n"
            . "- Forwext requirement: " . $forwextVersion . "\n"
            . "- Package manifest: addon.json\n";

        $files = [
            'addon.json'=>$manifestJson,
            'composer.json'=>$composerJson,
            'README.md'=>$readme,
            'src/Extension.php'=>$extension,
            'migrations/.gitkeep'=>'',
            'resources/.gitkeep'=>'',
            'tests/.gitkeep'=>'',
        ];

        $written = [];
        try {
            foreach ($files as $relative=>$content) {
                $path = $target . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relative);
                $this->writeNewFile($path, $content);
                $written[] = str_replace(DIRECTORY_SEPARATOR, '/', substr($path, strlen($root) + 1));
            }
        } catch (\Throwable $exception) {
            $this->removeTree($target);
            throw $exception;
        }

        sort($written, SORT_STRING);

        return $written;
    }

    private function projectRoot(): string
    {
        $root = realpath($this->projectRoot);
        if (!is_string($root) || !is_dir($root) || is_link($root)) {
            throw new InvalidArgumentException('Forwext project root is invalid.');
        }
        if (!is_file($root . DIRECTORY_SEPARATOR . 'VERSION')) {
            throw new InvalidArgumentException('Forwext project root does not contain VERSION.');
        }

        return $root;
    }

    private function ensureDirectory(string $directory): void
    {
        if (is_link($directory)) {
            throw new RuntimeException('Scaffold directory may not be a symbolic link.');
        }
        if (!is_dir($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create scaffold directory.');
        }
    }

    private function writeNewFile(string $path, string $content): void
    {
        $directory = dirname($path);
        $this->ensureDirectory($directory);
        if (file_exists($path) || is_link($path)) {
            throw new RuntimeException('Refusing to overwrite generated file: ' . $path);
        }
        if (file_put_contents($path, $content, LOCK_EX) !== strlen($content)) {
            throw new RuntimeException('Unable to write generated file: ' . $path);
        }
    }

    private function removeTree(string $path): void
    {
        if (!is_dir($path) || is_link($path)) {
            return;
        }
        $items = scandir($path);
        if (!is_array($items)) {
            return;
        }
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $child = $path . DIRECTORY_SEPARATOR . $item;
            if (is_dir($child) && !is_link($child)) {
                $this->removeTree($child);
            } else {
                @unlink($child);
            }
        }
        @rmdir($path);
    }
}
