<?php

declare(strict_types=1);

use Forwext\Core\Api\V1\ApiV1EndpointDefinition;
use Forwext\Core\Api\V1\ApiV1EndpointRegistry;
use Forwext\Core\Api\V1\ApiV1Resource;
use Forwext\Core\Api\V1\ApiV1Scope;
use Forwext\Core\Http\HttpMethod;

$root=dirname(__DIR__);
require $root.'/vendor/autoload.php';

$target=$root.'/packages/sdk/src/generated/contract.ts';
$check=in_array('--check',$argv,true);

$endpoints=[];
foreach(ApiV1EndpointRegistry::coreDefaults()->all() as $endpoint){
    if(!$endpoint instanceof ApiV1EndpointDefinition){
        throw new RuntimeException('API registry returned an invalid endpoint definition.');
    }
    $endpoints[$endpoint->routeName]=[
        'path'=>$endpoint->path,
        'methods'=>array_map(
            static fn(HttpMethod $method):string=>$method->value,
            $endpoint->methods,
        ),
        'operation'=>$endpoint->operation->value,
        'resource'=>$endpoint->resource?->value,
        'scope'=>$endpoint->scope?->value,
        'public'=>$endpoint->public,
    ];
}
ksort($endpoints,SORT_STRING);

$contract=[
    'version'=>'v1',
    'resources'=>array_map(static fn(ApiV1Resource $value):string=>$value->value,ApiV1Resource::cases()),
    'scopes'=>array_map(static fn(ApiV1Scope $value):string=>$value->value,ApiV1Scope::cases()),
    'endpoints'=>$endpoints,
];

$json=json_encode(
    $contract,
    JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR,
);
$content="/* This file is generated by tools/generate-api-v1-sdk-contract.php. Do not edit manually. */\n"
    ."export const FORWEXT_API_CONTRACT = ".$json." as const;\n\n"
    ."export type ForwextApiVersion = typeof FORWEXT_API_CONTRACT.version;\n"
    ."export type ForwextApiResource = typeof FORWEXT_API_CONTRACT.resources[number];\n"
    ."export type ForwextApiScope = typeof FORWEXT_API_CONTRACT.scopes[number];\n"
    ."export type ForwextApiEndpointName = keyof typeof FORWEXT_API_CONTRACT.endpoints;\n"
    ."export type ForwextApiEndpoint = typeof FORWEXT_API_CONTRACT.endpoints[ForwextApiEndpointName];\n";

if($check){
    $existing=is_file($target)?file_get_contents($target):false;
    if(!is_string($existing)||$existing!==$content){
        fwrite(STDERR,"Generated TypeScript API contract is stale. Run npm run sdk:generate.\n");
        exit(1);
    }
    echo "Generated TypeScript API contract is current.\n";
    exit(0);
}

$directory=dirname($target);
if(!is_dir($directory)&&!mkdir($directory,0775,true)&&!is_dir($directory)){
    throw new RuntimeException('Unable to create SDK generated contract directory.');
}
if(file_put_contents($target,$content)!==strlen($content)){
    throw new RuntimeException('Unable to write generated TypeScript API contract.');
}
echo "Generated packages/sdk/src/generated/contract.ts.\n";
