<?php

declare(strict_types=1);

use Forwext\Core\Ui\DesignToken\DesignTokenCatalog;
use Forwext\Core\Ui\DesignToken\DesignTokenDefinition;

$root=dirname(__DIR__);
require $root.'/vendor/autoload.php';

$target=$root.'/packages/react-ui/src/generated/design-tokens.ts';
$check=in_array('--check',$argv,true);

$tokens=array_map(
    static fn(DesignTokenDefinition $definition):array=>[
        'key'=>$definition->key,
        'cssVariable'=>$definition->cssVariable(),
    ],
    DesignTokenCatalog::coreDefaults()->definitions(),
);
usort($tokens,static fn(array $left,array $right):int=>$left['key']<=>$right['key']);

$json=json_encode(
    $tokens,
    JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR,
);
$content="/* This file is generated by tools/generate-react-design-token-contract.php. Do not edit manually. */\n"
    ."export const FORWEXT_CORE_DESIGN_TOKENS = ".$json." as const;\n\n"
    ."export type ForwextCoreDesignTokenKey = (typeof FORWEXT_CORE_DESIGN_TOKENS)[number][\"key\"];\n\n"
    ."export const FORWEXT_CORE_DESIGN_TOKEN_CSS_VARIABLES = Object.fromEntries(\n"
    ."  FORWEXT_CORE_DESIGN_TOKENS.map((token) => [token.key, token.cssVariable]),\n"
    .") as Record<ForwextCoreDesignTokenKey, string>;\n";

if($check){
    $existing=is_file($target)?file_get_contents($target):false;
    if(!is_string($existing)||$existing!==$content){
        fwrite(STDERR,"Generated React design-token contract is stale. Run npm run react-ui:generate.\n");
        exit(1);
    }
    echo "Generated React design-token contract is current.\n";
    exit(0);
}

$directory=dirname($target);
if(!is_dir($directory)&&!mkdir($directory,0775,true)&&!is_dir($directory)){
    throw new RuntimeException('Unable to create React design-token contract directory.');
}
if(file_put_contents($target,$content)!==strlen($content)){
    throw new RuntimeException('Unable to write React design-token contract.');
}
echo "Generated packages/react-ui/src/generated/design-tokens.ts.\n";
